server:
  port: 80
  servlet:
#    context-path=/web-app
    encoding:
      force-response: true
spring:
  servlet:
    multipart:
      max-file-size: 2048KB
      max-request-size: 2048KB
  datasource:
    url: jdbc:h2:file:./data/vavishka
    #    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  resources:
    cache: false
    cache.period: 0
  template:
    cache: false
storage:
  location: c:/upload-dir
  groups:
    sample:
      folder: sample
      width: 640
      height: 640
      sql: insert into header (path, orders) values (?, ?)
    header:
      folder: header
      width: 640
      height: 640
      sql: insert into header (path, orders) values (?, ?)
app:
  mode:
    debug: true
image-loader:
  groups:
    header: select path, orders from header where id in (select id from (SELECT max(id) id, orders FROM header GROUP BY orders))
static-resource:
  paths:
    '[/**]':
      - classpath:/public/
      - classpath:/static/
      - file:///c:/upload-dir/
sql:
  groups:
    sample:
      insert: insert into samples (title, description, imageSrc) values(?, ?, ?)
      select: select title, description, imageSrc from samples