server:
  port: 80
  servlet:
    session:
      timeout: 360
spring:
  datasource:
    url: jdbc:h2:file:./data/vavishka
#    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
app:
  mode:
    debug: true
